version: '3.8'
services:
  db:
    container_name: postgres_db
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - db_network

  appseed-app:
    container_name: appseed_app
    restart: always
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8001:8000"
    networks:
      - db_network
      - web_network
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres_db:5432/mydatabase

  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - ./nginx/appseed-app.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web_network
    depends_on: 
      - appseed-app

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge

volumes:
  postgres_data:
