version: '3.8'
services:
  db:
    container_name: postgres_db
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - db_network

  smartsignal_app:
    container_name: smartsignal_app
    restart: always
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    networks:
      - db_network
      - web_network
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres_db:5432/mydatabase

  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "5085:80"  # Nginx poort configureren om verkeer op poort 80 te proxy'en
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - smartsignal_app

networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge

volumes:
  postgres_data:
